# Setup
title: 'FAUniversity Galleries'
tagline: 
url: https://fau.thankyoudom.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .editorconfig
  - .git
  - .jekyll-cache
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Dominique
  url: https://twitter.com/thankyoudom
  email: thankyoudom@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
 

  - title: About
    url: /about

 